In [1]:
import torch
import numpy as np

In [45]:
torch.cuda.is_available(), torch.cuda.current_device(),torch.cuda.device_count(),torch.cuda.get_device_capability(0), torch.cuda.get_device_name(0)

(True, 0, 1, (6, 1), 'Quadro P520')

In [46]:
torch.cuda.is_initialized()

True

In [4]:
!nvidia-smi

Wed Apr 14 14:55:43 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 452.66       Driver Version: 452.66       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P520        WDDM  | 00000000:2D:00.0 Off |                  N/A |
| N/A   56C    P8    N/A /  N/A |     64MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [12]:
some_data = [[1,2], [3,4]]
some_data

[[1, 2], [3, 4]]

In [13]:
type(some_data)

list

In [14]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [15]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

In [16]:
some_data = torch.tensor(some_data)
some_data

tensor([[1, 2],
        [3, 4]])

In [17]:
type(some_data)

torch.Tensor

In [19]:
some_data.dtype, some_data.shape

(torch.int64, torch.Size([2, 2]))

In [20]:
numpy_array = np.random.rand(3,4)
numpy_array

array([[0.59887585, 0.01337057, 0.26309221, 0.0550977 ],
       [0.76346442, 0.92554987, 0.44311126, 0.44477397],
       [0.55019603, 0.28706011, 0.01694184, 0.48970652]])

In [21]:
torch.from_numpy(numpy_array)

tensor([[0.5989, 0.0134, 0.2631, 0.0551],
        [0.7635, 0.9255, 0.4431, 0.4448],
        [0.5502, 0.2871, 0.0169, 0.4897]], dtype=torch.float64)

In [22]:
torch.tensor(numpy_array)

tensor([[0.5989, 0.0134, 0.2631, 0.0551],
        [0.7635, 0.9255, 0.4431, 0.4448],
        [0.5502, 0.2871, 0.0169, 0.4897]], dtype=torch.float64)

In [23]:
torch.from_numpy(numpy_array) == torch.tensor(numpy_array)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [26]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
my_tensor = torch.rand(3,4)
my_tensor

tensor([[0.2691, 0.5107, 0.7186, 0.5500],
        [0.0591, 0.9268, 0.4005, 0.1163],
        [0.2452, 0.7553, 0.0773, 0.9131]])

In [34]:
my_tensor.dtype, my_tensor.device

(torch.float32, device(type='cpu'))

In [52]:
my_tensor = my_tensor.to("cuda")
my_tensor.device

device(type='cuda', index=0)

In [53]:
my_tensor[:,1:3]

tensor([[0.5107, 0.7186],
        [0.9268, 0.4005],
        [0.7553, 0.0773]], device='cuda:0')

In [54]:
my_tensor.mul(my_tensor)

tensor([[0.0724, 0.2608, 0.5164, 0.3025],
        [0.0035, 0.8590, 0.1604, 0.0135],
        [0.0601, 0.5705, 0.0060, 0.8337]], device='cuda:0')

In [55]:
my_tensor * my_tensor

tensor([[0.0724, 0.2608, 0.5164, 0.3025],
        [0.0035, 0.8590, 0.1604, 0.0135],
        [0.0601, 0.5705, 0.0060, 0.8337]], device='cuda:0')

In [59]:
my_tensor.matmul(my_tensor.T)

tensor([[1.1521, 0.8410, 1.0094],
        [0.8410, 1.0364, 0.8516],
        [1.0094, 0.8516, 1.4702]], device='cuda:0')

In [61]:
my_tensor @ my_tensor.T

tensor([[1.1521, 0.8410, 1.0094],
        [0.8410, 1.0364, 0.8516],
        [1.0094, 0.8516, 1.4702]], device='cuda:0')

In [62]:
torch.matmul(my_tensor,my_tensor.T)

tensor([[1.1521, 0.8410, 1.0094],
        [0.8410, 1.0364, 0.8516],
        [1.0094, 0.8516, 1.4702]], device='cuda:0')

In [63]:
my_tensor.sum(0)

tensor([0.5734, 2.1928, 1.1964, 1.5793], device='cuda:0')

In [64]:
my_tensor.sum()

tensor(5.5419, device='cuda:0')

In [65]:
torch.cat([my_tensor,my_tensor])

tensor([[0.2691, 0.5107, 0.7186, 0.5500],
        [0.0591, 0.9268, 0.4005, 0.1163],
        [0.2452, 0.7553, 0.0773, 0.9131],
        [0.2691, 0.5107, 0.7186, 0.5500],
        [0.0591, 0.9268, 0.4005, 0.1163],
        [0.2452, 0.7553, 0.0773, 0.9131]], device='cuda:0')

In [67]:
torch.nn.functional.softmax(my_tensor,1)

tensor([[0.1936, 0.2465, 0.3035, 0.2564],
        [0.1710, 0.4073, 0.2406, 0.1811],
        [0.1831, 0.3050, 0.1548, 0.3571]], device='cuda:0')

In [69]:
torch.nn.functional.softmax(my_tensor,1).sum(1)

tensor([1., 1., 1.], device='cuda:0')

In [70]:
my_tensor.clip(0.2,0.8)

tensor([[0.2691, 0.5107, 0.7186, 0.5500],
        [0.2000, 0.8000, 0.4005, 0.2000],
        [0.2452, 0.7553, 0.2000, 0.8000]], device='cuda:0')

In [71]:
my_tensor.cpu().detach().numpy()

array([[0.26907104, 0.51071477, 0.71858954, 0.5499773 ],
       [0.05912554, 0.9268323 , 0.40045625, 0.11625487],
       [0.24521971, 0.7552901 , 0.07732952, 0.91305643]], dtype=float32)