In [42]:
import torch

In [43]:
a = torch.tensor([5.], requires_grad = True)
b = torch.tensor([6.], requires_grad = True)
a,b

(tensor([5.], requires_grad=True), tensor([6.], requires_grad=True))

In [44]:
y = a**3 - b**2
y

tensor([89.], grad_fn=<SubBackward0>)

In [45]:
print(a.grad, b.grad)

None None


In [46]:
y.backward()
a.grad, b.grad

(tensor([75.]), tensor([-12.]))

In [47]:
W = torch.randn(10,1,requires_grad = True)
b = torch.randn(1,requires_grad = True)

X = torch.rand(1,10)

In [48]:
output = torch.matmul(X, W) + b
loss = 1 - output
output, loss

(tensor([[-0.5748]], grad_fn=<AddBackward0>),
 tensor([[1.5748]], grad_fn=<RsubBackward1>))

In [49]:
loss.backward()

In [50]:
W.grad

tensor([[-0.3697],
        [-0.4570],
        [-0.4577],
        [-0.2341],
        [-0.1457],
        [-0.4104],
        [-0.7547],
        [-0.6310],
        [-0.6510],
        [-0.9687]])

In [51]:
b.grad

tensor([-1.])

In [52]:
with torch.no_grad():
    W = W - 0.1 * W.grad.data
    b = b - 0.1 * b.grad.data


In [53]:

b,W

(tensor([-2.2230]),
 tensor([[ 2.9624],
         [-0.1921],
         [-0.7422],
         [-1.8105],
         [-0.6717],
         [-1.2552],
         [ 0.0932],
         [-0.6762],
         [ 1.4467],
         [ 1.9044]]))