In [1]:
import torch

In [2]:
a = torch.tensor([5.], requires_grad = True)
b = torch.tensor([6.], requires_grad = True)
a,b

(tensor([5.], requires_grad=True), tensor([6.], requires_grad=True))

In [3]:
y = a**3 - b**2
y

tensor([89.], grad_fn=<SubBackward0>)

In [4]:
print(a.grad, b.grad)

None None


In [5]:
y.backward()
a.grad, b.grad

(tensor([75.]), tensor([-12.]))

In [6]:
W = torch.randn(10,1,requires_grad = True)
b = torch.randn(1,requires_grad = True)

X = torch.rand(1,10)

In [7]:
output = torch.matmul(X, W) + b
loss = 1 - output
output, loss

(tensor([[2.3224]], grad_fn=<AddBackward0>),
 tensor([[-1.3224]], grad_fn=<RsubBackward1>))

In [8]:
loss.backward()

In [9]:
W.grad

tensor([[-0.0742],
        [-0.1618],
        [-0.2833],
        [-0.5541],
        [-0.8227],
        [-0.2950],
        [-0.5779],
        [-0.4701],
        [-0.6343],
        [-0.0753]])

In [10]:
b.grad

tensor([-1.])

In [11]:
with torch.no_grad():
    W = W - 0.1 * W.grad.data
    b = b - 0.1 * b.grad.data


In [12]:

b,W

(tensor([0.1294]),
 tensor([[-0.7282],
         [-2.2132],
         [ 0.4586],
         [-0.0650],
         [ 0.9599],
         [ 0.4171],
         [ 0.6672],
         [ 0.8540],
         [ 1.7569],
         [ 0.1543]]))