In [1]:
import torch
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [2]:
class CustomDataset:
    def __init__(self, data, targets):
        self.data = data
        self.targets = targets
        
    def __len__(self):
#         return len(self.data)
        return self.data.shape[0]
    
    def __getitem__(self, idx):
        current_sample = self.data[idx,:]
        current_target = self.targets[idx]
        
        return {
            "X":torch.tensor(current_sample,dtype=torch.float),
            "y":torch.tensor(current_target,dtype=torch.long)
        }

In [3]:
data, targets = make_classification(n_samples=1000,n_features=20)
data.shape, targets.shape

((1000, 20), (1000,))

In [4]:
train_data, test_data, train_targets, test_targets = train_test_split(data, targets, 
                                                                      stratify=targets)

train_data.shape, test_data.shape, train_targets.shape, test_targets.shape

((750, 20), (250, 20), (750,), (250,))

In [5]:
train_dataset = CustomDataset(train_data, train_targets)
test_dataset = CustomDataset(test_data, test_targets)

In [6]:
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size = 4)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size = 4)

In [7]:
model = lambda X,w, b: torch.matmul(X,w) + b

W = torch.randn(20,1,requires_grad = True)
b = torch.randn(1,requires_grad = True)
lr = 0.001

for epoch in range(10):
    epoch_loss = 0
    for data in train_loader:
        Xtrain = data["X"]
        ytrain = data["y"]
        output =model(Xtrain, W, b)
        loss = torch.mean((ytrain.view(-1) - output.view(-1)) ** 2)
        epoch_loss = epoch_loss + loss.item()
        loss.backward()
        
        with torch.no_grad():
            W = W - lr * W.grad
            b = b - lr * b.grad

        W.requires_grad_(True)
        b.requires_grad_(True)
    
    print(epoch, epoch_loss)


0 1708.6390960812569
1 684.7209814488888
2 308.720470815897
3 155.17274264991283
4 86.80632527731359
5 54.35724734328687
6 38.23926241789013
7 29.967598326969892
8 25.6182079045102
9 23.287381122121587


In [8]:
W

tensor([[ 0.0208],
        [ 0.0088],
        [-0.5636],
        [ 0.0054],
        [-0.0761],
        [-0.0235],
        [-0.0410],
        [ 0.0395],
        [-0.0009],
        [ 0.0688],
        [ 0.0054],
        [-0.0169],
        [-0.8512],
        [-0.0476],
        [-0.2553],
        [-0.0291],
        [ 0.0118],
        [-0.0279],
        [ 0.0135],
        [-0.0279]], requires_grad=True)

In [9]:
b 

tensor([0.4466], requires_grad=True)

In [10]:
model = lambda X,w, b: torch.matmul(X,w) + b

W = torch.randn(20,1,requires_grad = True)
b = torch.randn(1,requires_grad = True)
lr = 0.001

for epoch in range(10):
    epoch_loss = 0
    counter = 0
    for data in train_loader:
        Xtrain = data["X"]
        ytrain = data["y"]
        output =model(Xtrain, W, b)
        loss = torch.mean((ytrain.view(-1) - output.view(-1)) ** 2)
        epoch_loss = epoch_loss + loss.item()
        loss.backward()
        
        with torch.no_grad():
            W = W - lr * W.grad
            b = b - lr * b.grad

        W.requires_grad_(True)
        b.requires_grad_(True)
        counter += 1
    
    print(epoch, epoch_loss/counter)


0 9.40910047752426
1 4.461265639976618
2 2.173153309825253
3 1.1001550072526678
4 0.590424068519806
5 0.34533210010565024
6 0.22614342223684442
7 0.16755871699895075
8 0.13846698890568965
9 0.12387634298090447


In [11]:
fc_layer = torch.nn.Linear(in_features=20, out_features=1)
fc_layer.weight.shape

torch.Size([1, 20])

In [13]:
fc_layer.bias

Parameter containing:
tensor([-0.0920], requires_grad=True)